name: OvercastMapPacker
author: WesJD
desc: Writes map XMLs for Overcast Network maps from in-game GUIs
website: https://github.com/WesJD/OvercastMapPacker
main: OvercastMapPacker
version: ${version}
commands:
  xml:
